name: Build Packer Template

on:
  push:
    branches:
      - main

jobs:
  build-and-share-ami:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Packer
        run: |
          packer plugins install github.com/hashicorp/amazon
          packer version

      - name: Build AMI
        run: |
          packer build ami.debian-packer-aws.pkr.hcl
          env:
            AWS_REGION: us-east-1
            SSH_USERNAME: admin
            SUBNET_ID: subnet-025f87a6da259c0bd
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
